### ISSUE TITLE
scGate multi cells parameter in Run.HiTME

### ISSUE THREAD

**Issue by NoemieL** [carmonalab/HiTME#17] opened 2024-04-15 17:15 UTC
Hello,

Thanks again for creating this package. When using scGate alone, we have the option to choose whether the cell called as Multi should be considered as NA or not. This option is not included in Run.HiTME. Could you please include this parameter in the Run.HiTME function to be able to get the scGate multi cell.

Thanks

**Comment by halterc** [comment] 2024-04-18 07:35
Hi Noemi,

Thank you for the feedback. Good point!
We will include this option HiTME version 1.3, which is currently in development, together with many new useful features. It will be released within the next few days. I'll let you know as soon as it's released.

Cheers,
Chris

**Comment by halterc** [comment] 2024-04-19 09:54
Hi Noemi,

If you want to use Run>HiTME with multi.asNA = FALSE, now you can.
We implemented it in 599dfbf.

You can install the latest version from the 'dev' branch like so:
```
install.packages("remotes")
remotes::install_github("carmonalab/HiTME",ref="f4c94b5", force = T)
```

We will update the tutorial highlighting the new features soon.
PS: be aware that some functions might have been updated in the newest versions. So, if some code does not work any more, please check the documentation with e.g. `?Run.HiTME`.

Best,
Chris

**Closed by halterc** 2024-04-19 09:54 UTC
Labels: enhancement

**Comment by NoemieL** [comment] 2024-04-19 22:28
Hi Chris,

Thank you very much for including it so rapidly. Appreciate it!

Best,
Noemie

**Comment by NoemieL** [comment] 2024-04-22 01:43
Hi Chris,

I can't install the new version with the option because it requiered scGate version 1.6.1 and I can only get version 1.6.0. Could you please share it?

Thanks,
Noémie

**Comment by halterc** [comment] 2024-04-22 06:51
Hi Noémie,

sure, no problem. You can install it from github like so:
```
install.packages("remotes")
remotes::install_github("carmonalab/scGate", force=T)
```

Best,
Chris

**Comment by NoemieL** [comment] 2024-04-24 17:37
Hi Chris,

Thanks, I was able to install the new version of scGate. I ran HiTME with the new parameter multi.asNA = FALSE and with or without useNA = "ifany", but in both cases I didn't get multiple cells. When I ran scGate alone, I got multiple cells. Do you know why multi cells are not detected by HiTME compared to scGate? I have attached the code used for both packages.
Thanks for your help.

Best,

Noemie

**Using HiTME:**
```
library(scGate)
library(ProjecTILs)
library(HiTME)
library(BiocParallel)

scGate_models_DB <- get_scGateDB(branch = "master")
models.HiTME <- scGate_models_DB$human$HiTME

ref.maps <- list(CD8 = load.reference.map("/storage/Noemie/Dara_analysis_Paper/ProjecTIL/CD8T_human_ref_v1_1.rds"),
                 CD4 = load.reference.map("/storage/Noemie/Dara_analysis_Paper/ProjecTIL/CD4T_human_ref_v2.rds"),
                 DC = load.reference.map("/storage/Noemie/Dara_analysis_Paper/ProjecTIL/DC_human_ref_v1.rds"),
                 MoMac = load.reference.map("/storage/Noemie/Dara_analysis_Paper/ProjecTIL/MoMac_human_v1.rds")
)

layer1.links <- list("CD8" = "CL:0000625",
                     "CD4" = "CL:0000624",
                     "DC" = "CL:0000451",
                     "MoMac" = "CL:0000576_CL:0000235"
)

for(a in names(ref.maps)){
  ref.maps[[a]]@misc$layer1_link <- layer1.links[[a]]
}

DefaultAssay(merged_seurat_STACAS_CellRanger)="RNA"
annotated.merged_seurat <- Run.HiTME(merged_seurat_STACAS_CellRanger,
                           scGate.model = models.HiTME,
                           ref.maps = ref.maps,
                           # already split object
                           split.by = "sample",
                           return.Seurat=TRUE,
                           # link between scGate and ProjecTILs
                           layer1_link = "CellOntology_ID",
                           # paralelization parameters
                           ncores = 50,
                           progressbar = TRUE,
                           #useNA = "ifany",
                           multi.asNA=FALSE
)
table(annotated.merged_seurat$scGate_multi, useNA = "ifany")

        Bcell          CD4T          CD8T   Endothelial    Epithelial   Erythrocyte    Fibroblast          Mast 
        12888         38959         34975             0             0          6438            12            22 
Megakaryocyte         MoMac   Neutrophils            NK         panDC    PlasmaCell          <NA> 
          144         30339           348         12864          3316         86945         52433  
```

**Using scGate alone:**
```
merged_seurat_STACAS_CellRanger <- scGate(merged_seurat_STACAS_CellRanger, model = models.HiTME,ncores = 50,multi.asNA = FALSE,reduction = "umap")

table(merged_seurat_STACAS_CellRanger$scGate_multi, useNA = "ifany")

        Bcell          CD4T          CD8T   Erythrocyte    Fibroblast          Mast Megakaryocyte         MoMac 
        12767         39344         35251          7117           128            70           325         30956 
        Multi   Neutrophils            NK         panDC    PlasmaCell          <NA> 
         1675           463         13287          3551         86932         47817
```
Here is my session info:

```
sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Edmonton
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BiocParallel_1.34.2 HiTME_1.3.0         ProjecTILs_3.3.1    scGate_1.6.2        DoubletFinder_2.0.4
 [6] dplyr_1.1.4         ggplot2_3.5.0       Seurat_5.0.0        SeuratObject_5.0.1  sp_2.1-3           

loaded via a namespace (and not attached):
  [1] IRanges_2.34.1              R.methodsS3_1.8.2           progress_1.2.3             
  [4] nnet_7.3-19                 goftest_1.2-3               Biostrings_2.68.1          
  [7] TH.data_1.1-2               vctrs_0.6.5                 spatstat.random_3.2-3      
 [10] digest_0.6.35               png_0.1-8                   corpcor_1.6.10             
 [13] ggrepel_0.9.5               deldir_2.0-4                parallelly_1.37.1          
 [16] MASS_7.3-60                 reshape2_1.4.4              httpuv_1.6.15              
 [19] foreach_1.5.2               BiocGenerics_0.48.1         withr_3.0.0                
 [22] ggpubr_0.6.0                survival_3.5-5              memoise_2.0.1              
 [25] zoo_1.8-12                  pbapply_1.7-2               R.oo_1.26.0                
 [28] prettyunits_1.2.0           KEGGREST_1.40.1             promises_1.3.0             
 [31] SignatuR_0.2.1              httr_1.4.7                  rstatix_0.7.2              
 [34] globals_0.16.3              fitdistrplus_1.1-11         rstudioapi_0.16.0          
 [37] miniUI_0.1.1.1              generics_0.1.3              curl_5.2.1                 
 [40] S4Vectors_0.38.2            zlibbioc_1.46.0             ScaledMatrix_1.10.0        
 [43] ggraph_2.2.1                polyclip_1.10-6             TFisher_0.2.0              
 [46] GenomeInfoDbData_1.2.10     SparseArray_1.2.4           xtable_1.8-4               
 [49] stringr_1.5.1               pracma_2.4.4                S4Arrays_1.2.1             
 [52] BiocFileCache_2.8.0         hms_1.1.3                   GenomicRanges_1.52.1       
 [55] irlba_2.3.5.1               colorspace_2.1-0            filelock_1.0.3             
 [58] ROCR_1.0-11                 reticulate_1.35.0           spatstat.data_3.0-4        
 [61] magrittr_2.0.3              lmtest_0.9-40               later_1.3.2                
 [64] viridis_0.6.5               lattice_0.21-8              spatstat.geom_3.2-9        
 [67] future.apply_1.11.2         scattermore_1.2             XML_3.99-0.16.1            
 [70] scuttle_1.10.3              cowplot_1.1.3               matrixStats_1.3.0          
 [73] RcppAnnoy_0.0.22            class_7.3-22                pillar_1.9.0               
 [76] nlme_3.1-162                iterators_1.0.14            compiler_4.3.1             
 [79] beachmat_2.18.1             RSpectra_0.16-1             stringi_1.8.3              
 [82] gower_1.0.1                 tensor_1.5                  SummarizedExperiment_1.30.2
 [85] lubridate_1.9.3             plyr_1.8.9                  crayon_1.5.2               
 [88] abind_1.4-5                 ggdendro_0.2.0              sn_2.1.1                   
 [91] locfit_1.5-9.9              graphlayouts_1.1.1          bit_4.0.5                  
 [94] mathjaxr_1.6-0              sandwich_3.1-0              codetools_0.2-19           
 [97] multcomp_1.4-25             recipes_1.0.10              BiocSingular_1.18.0        
[100] plotly_4.10.4               multtest_2.56.0             mime_0.12                  
[103] splines_4.3.1               Rcpp_1.0.12                 fastDummies_1.7.3          
[106] dbplyr_2.5.0                sparseMatrixStats_1.14.0    blob_1.2.4                 
[109] utf8_1.2.4                  listenv_0.9.1               DelayedMatrixStats_1.24.0  
[112] Rdpack_2.6                  ggsignif_0.6.4              tibble_3.2.1               
[115] Matrix_1.6-5                statmod_1.5.0               tweenr_2.0.3               
[118] pkgconfig_2.0.3             pheatmap_1.0.12             tools_4.3.1                
[121] cachem_1.0.8                rbibutils_2.2.16            RSQLite_2.3.6              
[124] viridisLite_0.4.2           DBI_1.2.2                   numDeriv_2016.8-1.1        
[127] fastmap_1.1.1               scales_1.3.0                grid_4.3.1                 
[130] ica_1.0-3                   metap_1.10                  broom_1.0.5                
[133] patchwork_1.2.0             dotCall64_1.1-1             carData_3.0-5              
[136] RANN_2.6.1                  rpart_4.1.19                farver_2.1.1               
[139] tidygraph_1.3.1             MatrixGenerics_1.14.0       cli_3.6.2                  
[142] purrr_1.0.2                 stats4_4.3.1                UCell_2.7.7                
[145] leiden_0.4.3.1              lifecycle_1.0.4             caret_6.0-94               
[148] Hotelling_1.0-8             uwot_0.1.16                 Biobase_2.60.0             
[151] mvtnorm_1.2-4               bluster_1.10.0              lava_1.8.0                 
[154] backports_1.4.1             timechange_0.3.0            gtable_0.3.4               
[157] ggridges_0.5.6              progressr_0.14.0            parallel_4.3.1             
[160] pROC_1.18.5                 limma_3.56.2                jsonlite_1.8.8             
[163] edgeR_3.42.4                RcppHNSW_0.6.0              bitops_1.0-7               
[166] bit64_4.0.5                 qqconf_1.3.2                Rtsne_0.17                 
[169] spatstat.utils_3.0-4        BiocNeighbors_1.18.0        mutoss_0.1-13              
[172] metapod_1.8.0               dqrng_0.3.2                 R.utils_2.12.3             
[175] timeDate_4032.109           lazyeval_0.2.2              shiny_1.8.1.1              
[178] htmltools_0.5.8.1           sctransform_0.4.1           rappdirs_0.3.3             
[181] rrapply_1.2.6               data.tree_1.1.0             glue_1.7.0                 
[184] factoextra_1.0.7            spam_2.10-0                 XVector_0.40.0             
[187] RCurl_1.98-1.14             scran_1.30.2                mnormt_2.1.1               
[190] gridExtra_2.3               igraph_2.0.3                R6_2.5.1                   
[193] tidyr_1.3.1                 DESeq2_1.40.2               SingleCellExperiment_1.22.0
[196] STACAS_2.2.2                cluster_2.1.4               GenomeInfoDb_1.36.4        
[199] ipred_0.9-14                DelayedArray_0.28.0         tidyselect_1.2.1           
[202] plotrix_3.8-4               ggforce_0.4.2               xml2_1.3.6                 
[205] car_3.1-2                   AnnotationDbi_1.62.2        future_1.33.2              
[208] ModelMetrics_1.2.2.2        rsvd_1.0.5                  munsell_0.5.1              
[211] KernSmooth_2.23-21          data.table_1.15.4           htmlwidgets_1.6.4          
[214] RColorBrewer_1.1-3          biomaRt_2.56.1              rlang_1.1.3                
[217] spatstat.sparse_3.0-3       spatstat.explore_3.2-7      remotes_2.5.0              
[220] fansi_1.0.6                 hardhat_1.3.1               prodlim_2023.08.28 
```

**Comment by halterc** [comment] 2024-04-25 13:56
Hi Noemie,

you are right. Thank you for reporting the bug.
I just tested it and can confirm that using `multi.asNA = FALSE` was not working as intended yet.
I fixed and tested it. It should be working now.
You can download the latest version from the dev branch with this command:
`remotes::install_github("carmonalab/HiTME", ref="6a0d033", force = T)`

If you have any further questions, bug reports or feature suggestions, please let me know and we'll try to implement it as soon as possible. :)

Best,
Chris

**Comment by NoemieL** [comment] 2024-04-26 15:38
Hi Chris,

Thank you very much for the rapid fix. I had a chance to run it yesterday and it works well! 

Best,
Noemie
